### ISSUE TITLE
Using for before and after handlers

### ISSUE THREAD

**Issue by DataGreed** [ajb413/pubnub-functions-mock#17]
Hi, is it possible to use the library to test before and after events?
Could you please describe how to do it? Thanks

**Comment by ajb413** [comment]
Yes! Use this in your test's `request` object instead of the `request` like shown in the readme. Also delete the response parameter.

```javascript
const fireRequestObject = {
  'headers': {},
  'status': 200,
  'message': {},
  'ok': function(message) {
    return new Promise((resolve) => {
      if (message === undefined) {
        message = '';
      }
      resolve({
        'message': message,
      });
    });
  },
  'abort': function(message) {
    return new Promise((reject) => {
      if (message === undefined) {
        message = '';
      }
      reject({
        'message': message,
      });
    });
  },
};
```

There are also some examples here that I have not got around to merging: https://github.com/ajb413/pubnub-functions-mock/tree/examples/examples/Override

**Comment by DataGreed** [comment]
@ajb413 thank you very much, got this working! Appreciate your work on the library. It's a shame that Pubnub did not make any proper mocking tools available themselves.
